server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: '03290329'
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: SH #cluster name
#        namespace: 7b0f67bc-5ce9-4dfa-8bd8-a15575ae72f3 #namespace ID
        ephemeral: false #是否临时实例

#eureka:
#  client:
#    service-url:  #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka/
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients:  #制定饥饿加载的服务名称
      - userservice
feign:
  client:
    config:
      default:
        loggerLevel: FULL
  httpclient:
    enabled: true #支持HttpClient的开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径最大连接数